### ISSUE TITLE
OP8-Pro kernel build request

### ISSUE THREAD

**Issue by invincible-man** [crdroidandroid/android_kernel_oneplus_sm8250#3]
Hello my friend, hope everything just fine with ya ..!

Would it be possible to make a build crdroid kernel 12.1 again but i just wish this time if you can **nuked binderfs and also enable hci uart_h4 and vhci** where i can turn hci0 thru bluebinder flawlessly..however i've had test this build on OS11 custom rom and it seemed everything was working awesome with NH.. Let me know if you can do that as well with the latest updated kernel caf and other new patches & features release can be added tho if any showing nowadays..
It would be highly appreciated if it can be uploaded on release section so i can fetch it accordingly..thx

**Comment by fKm86** [comment]
Sorry, I am completely out of developing at the moment. I won't work on anything right now. Cheers

**Comment by gwolf2u** [comment]
at the current time, there's no decision needed for this issue
